# Generated by Django 4.0.4 on 2022-05-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idMascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de mascota')),
                ('nomTipoMascota', models.CharField(max_length=50, verbose_name='Nombre tipo de las mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idMascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID tipo de producto')),
                ('nomTipoProducto', models.CharField(max_length=50, verbose_name='Nombre tipo del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nomProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('stock', models.IntegerField(verbose_name='Stock del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del producto')),
                ('tipoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peludos_petshop.tipomascota')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peludos_petshop.tipoproducto')),
            ],
        ),
    ]
