# Generated by Django 4.0.4 on 2022-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='tipomascota',
            name='idMascota',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de mascota'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='idMascota',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID tipo de producto'),
        ),
    ]
