# Generated by Django 4.0.4 on 2022-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomascota',
            name='fotoMascota',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
    ]
