# Generated by Django 4.0.4 on 2022-05-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0002_producto_fotoproducto_alter_tipomascota_idmascota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
