# Generated by Django 4.0.4 on 2022-06-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0004_rename_idmascota_tipoproducto_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripción del producto'),
            preserve_default=False,
        ),
    ]
