# Generated by Django 4.0.4 on 2022-06-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0005_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
