# Generated by Django 4.0.4 on 2022-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0006_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción del producto'),
        ),
    ]
