# Generated by Django 4.0.4 on 2022-06-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peludos_petshop', '0007_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='idProducto',
            new_name='idTipoProducto',
        ),
    ]
